name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: '16.14.0'
      - name: NPM Installation
        run: |
          cd website
          npm install

      - name: Build
        run: |
          cd website
          npm run build

      - name: Get the content of algolia.json as config
        id: algolia_config
        run: echo "::set-output name=config::$(cat algolia.json | jq -r tostring)"

      - name: Push indices to Algolia
        uses: signcl/docsearch-scraper-action@master
        env:
          APPLICATION_ID: 8E6LWK96JA
          API_KEY: 0285def6cfdb5ff895b665c604f0eead
          CONFIG: ${{ steps.algolia_config.outputs.config }}

  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.14.0'
      - name: NPM Installation
        run: |
          cd website
          npm install

      - name: Build
        run: |
          cd website
          npm run build
