name: CI
on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  develop:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Pull from Notion
        env:
          DOCS_NOTION_TOKEN: ${{ secrets.DOCS_NOTION_TOKEN }}
          DOCS_NOTION_ROOT_PAGE: ${{ secrets.DOCS_NOTION_ROOT_PAGE }}
        run: yarn pull

      - name: Commit New Source Material
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit content changes pulled from notion

      - name: Build
        run: yarn build
  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make changes to pull request
        run: date +%s > report.txt
      
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          commit-message: New post
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          base: release
          branch: develop
          delete-branch: false
          title: 'New post'
          body: |
            Update post
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/trungpq163/system32
          labels: |
            report
            automated pr
          assignees: trungpq163
          reviewers: trungpq163
          team-reviewers: |
            owners
            maintainers
          milestone: 1
          draft: false
