name: CI
on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  develop:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Pull from Notion
        env:
          DOCS_NOTION_TOKEN: ${{ secrets.DOCS_NOTION_TOKEN }}
          DOCS_NOTION_ROOT_PAGE: ${{ secrets.DOCS_NOTION_ROOT_PAGE }}
        run: yarn pull

      - name: Commit New Source Material
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit content changes pulled from notion

      - name: Create a pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: 'develop'
          destination_branch: 'release'
          github_token: ${{ secrets.AUTO_PR_TOKEN }}
          pr_title: 'Pull Request from develop to release'
          pr_body: ':crown: *An automated PR*'
          pr_label: 'auto-pr'

      - name: Build
        run: yarn build
  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
